<?php
namespace Tests\Feature;
use App\Models\ActivityLog;
use App\Models\Project;
use App\Models\Todo;
use App\Models\Treatment;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;
class ActivityLogTest extends TestCase{
 use RefreshDatabase;
 public function test_guest_cannot_access_activity_logs():void{$this->get('/activity-logs')->assertRedirect(route('login'));}
 public function test_user_can_create_and_view_activity_log_with_photos():void{Storage::fake('public');$user=User::factory()->create();$project=Project::factory()->for($user)->create();$todo=Todo::factory()->for($user)->create();$this->actingAs($user)->get('/activity-logs/create')->assertOk()->assertSee('できたこと・体調を記録する');$response=$this->post('/activity-logs',['title'=>'資料を完成させた','project_id'=>$project->id,'todo_id'=>$todo->id,'performed_on'=>'2026-08-25','performed_at'=>'14:30','duration_minutes'=>60,'memo'=>'よくできました','photos'=>[$this->fakePng('one.png'),$this->fakePng('two.png')]]);$log=ActivityLog::where('user_id',$user->id)->firstOrFail();$response->assertRedirect(route('activity-logs.show',$log));$this->assertSame(2,$log->photos()->count());foreach($log->photos as $photo)Storage::disk('public')->assertExists($photo->path);$this->get(route('activity-logs.show',$log))->assertOk()->assertSee('資料を完成させた')->assertSee('よくできました')->assertSee('60分');}
 public function test_user_can_record_condition_and_symptoms():void{$user=User::factory()->create();$this->actingAs($user)->post('/activity-logs',['title'=>'治療1日目','performed_on'=>'2026-08-25','condition'=>'hard','symptoms'=>['fatigue','nausea','diarrhea','constipation'],'memo'=>'午後から休みました'])->assertRedirect();$log=ActivityLog::where('user_id',$user->id)->firstOrFail();$this->assertSame('hard',$log->condition);$this->assertSame(['fatigue','nausea','diarrhea','constipation'],$log->symptoms);$this->get(route('activity-logs.show',$log))->assertOk()->assertSee('つらい')->assertSee('だるさ')->assertSee('吐き気')->assertSee('下痢')->assertSee('便秘');}
 public function test_user_can_link_condition_record_to_own_treatment():void{$user=User::factory()->create();$treatment=Treatment::create(['user_id'=>$user->id,'name'=>'AC療法','treatment_type'=>'chemotherapy','scheduled_on'=>'2026-09-10','cycle_number'=>2]);$this->actingAs($user)->get(route('activity-logs.create',['treatment_id'=>$treatment->id,'performed_on'=>'2026-09-10','title'=>'AC療法後の体調記録']))->assertOk()->assertSee('AC療法')->assertSee('value="2026-09-10"',false)->assertSee('value="AC療法後の体調記録"',false);$this->post('/activity-logs',['title'=>'AC療法後の体調記録','treatment_id'=>$treatment->id,'performed_on'=>'2026-09-10','condition'=>'hard','symptoms'=>['nausea']])->assertRedirect();$log=ActivityLog::where('user_id',$user->id)->firstOrFail();$this->assertSame($treatment->id,$log->treatment_id);$this->get(route('activity-logs.show',$log))->assertOk()->assertSee('治療後：AC療法')->assertSee('吐き気');}
 public function test_foreign_treatment_is_rejected():void{$user=User::factory()->create();$foreign=Treatment::create(['user_id'=>User::factory()->create()->id,'name'=>'他人の治療','treatment_type'=>'infusion','scheduled_on'=>'2026-09-10']);$this->actingAs($user)->post('/activity-logs',['title'=>'不正','treatment_id'=>$foreign->id,'performed_on'=>'2026-09-10'])->assertSessionHasErrors('treatment_id');$this->assertDatabaseMissing('activity_logs',['title'=>'不正']);}
 public function test_invalid_condition_and_symptom_are_rejected():void{$user=User::factory()->create();$this->actingAs($user)->post('/activity-logs',['title'=>'不正な体調','performed_on'=>'2026-08-25','condition'=>'unknown','symptoms'=>['unknown']])->assertSessionHasErrors(['condition','symptoms.0']);}
 public function test_foreign_project_and_todo_are_rejected():void{$user=User::factory()->create();$other=User::factory()->create();$project=Project::factory()->for($other)->create();$todo=Todo::factory()->for($other)->create();$this->actingAs($user)->post('/activity-logs',['title'=>'不正','project_id'=>$project->id,'todo_id'=>$todo->id,'performed_on'=>'2026-08-25'])->assertSessionHasErrors(['project_id','todo_id']);$this->assertDatabaseMissing('activity_logs',['title'=>'不正']);}
 public function test_list_only_shows_own_logs():void{$user=User::factory()->create();ActivityLog::factory()->for($user)->create(['title'=>'本人の記録']);ActivityLog::factory()->for(User::factory())->create(['title'=>'他人の記録']);$this->actingAs($user)->get('/activity-logs')->assertOk()->assertSee('本人の記録')->assertDontSee('他人の記録');}
 public function test_user_cannot_access_another_users_log_or_photo():void{Storage::fake('public');$user=User::factory()->create();$log=ActivityLog::factory()->for(User::factory())->create();$photo=$log->photos()->create(['disk'=>'public','path'=>'foreign.jpg']);$this->actingAs($user)->get(route('activity-logs.show',$log))->assertForbidden();$this->delete(route('activity-log-photos.destroy',$photo))->assertForbidden();$this->delete(route('activity-logs.destroy',$log))->assertForbidden();}
 public function test_photo_can_be_deleted_individually():void{Storage::fake('public');$user=User::factory()->create();$log=ActivityLog::factory()->for($user)->create();Storage::disk('public')->put('activity-logs/test.jpg','data');$photo=$log->photos()->create(['disk'=>'public','path'=>'activity-logs/test.jpg']);$this->actingAs($user)->delete(route('activity-log-photos.destroy',$photo))->assertSessionHas('status');Storage::disk('public')->assertMissing('activity-logs/test.jpg');$this->assertDatabaseMissing('activity_log_photos',['id'=>$photo->id]);}
 public function test_deleting_log_deletes_photo_files():void{Storage::fake('public');$user=User::factory()->create();$log=ActivityLog::factory()->for($user)->create();Storage::disk('public')->put('activity-logs/delete.jpg','data');$log->photos()->create(['disk'=>'public','path'=>'activity-logs/delete.jpg']);$this->actingAs($user)->delete(route('activity-logs.destroy',$log))->assertRedirect(route('activity-logs.index'));Storage::disk('public')->assertMissing('activity-logs/delete.jpg');$this->assertDatabaseMissing('activity_logs',['id'=>$log->id]);}
 public function test_no_more_than_five_photos_can_be_uploaded():void{Storage::fake('public');$user=User::factory()->create();$photos=[];for($i=0;$i<6;$i++)$photos[]=$this->fakePng("{$i}.png");$this->actingAs($user)->post('/activity-logs',['title'=>'多すぎる写真','performed_on'=>'2026-08-25','photos'=>$photos])->assertSessionHasErrors('photos');$this->assertDatabaseMissing('activity_logs',['title'=>'多すぎる写真']);}
 private function fakePng(string $name):UploadedFile{return UploadedFile::fake()->createWithContent($name,base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZefgAAAAASUVORK5CYII='));}
}
